"""
calendar.py — Academic calendar processing for Zaphod.

Converts a human-authored YAML/JSON calendar source into the
window.TRL_CALENDAR format consumed by Trillian components.

Ported from trillian/handoff/process-calendar.mjs.
"""

import json
from datetime import date, timedelta
from pathlib import Path

import yaml


# =============================================================================
# Core logic
# =============================================================================

def _parse_source(source_path: Path) -> dict:
    raw = source_path.read_text(encoding="utf-8")
    if source_path.suffix.lower() in (".yaml", ".yml"):
        return yaml.safe_load(raw)
    return json.loads(raw)


def _count_instruction_days(start: str, end: str, off: set) -> int:
    """Count weekdays in [start, end] inclusive, excluding dates in off."""
    cur = date.fromisoformat(start)
    last = date.fromisoformat(end)
    count = 0
    while cur <= last:
        if cur.weekday() < 5 and cur.isoformat() not in off:  # Mon–Fri
            count += 1
        cur += timedelta(days=1)
    return count


def process_calendar(source_path: Path) -> dict:
    """
    Parse source YAML/JSON, count instruction days per term, return
    a TRL_CALENDAR-shaped dict ready for emit_js() / emit_json().

    Also prints a summary report to stdout.
    Raises ValueError if totalInstructionDays is present and doesn't match.
    """
    source = _parse_source(source_path)

    print(f"\nProcessing {source['year']} calendar for {source['school']}")
    print("─" * 50)

    total_days = 0
    processed_terms = []

    for term in source.get("terms", []):
        holidays = term.get("holidays") or []
        # Normalise: bare string entries → {date, label}
        holidays = [
            {"date": h, "label": ""} if isinstance(h, str) else h
            for h in holidays
        ]
        off_set = {h["date"] for h in holidays}

        days = _count_instruction_days(term["start"], term["end"], off_set)
        total_days += days

        status = "✓" if days > 0 else "✗"
        print(f"{status}  {term['id'].ljust(16)} {days} days  ({term['start']} → {term['end']})")

        # Group consecutive holidays with the same label for compact output
        if holidays:
            grouped: list[tuple[str, str, int]] = []  # (date, label, count)
            for h in holidays:
                if grouped and grouped[-1][1] == h["label"]:
                    grouped[-1] = (grouped[-1][0], grouped[-1][1], grouped[-1][2] + 1)
                else:
                    grouped.append((h["date"], h["label"], 1))
            for hdate, hlabel, hcount in grouped:
                suffix = f"  (×{hcount})" if hcount > 1 else ""
                print(f"   off  {hdate}   {hlabel}{suffix}")

        processed_terms.append({
            "id":    term["id"],
            "name":  term["name"],
            "short": term["short"],
            "start": term["start"],
            "end":   term["end"],
            "days":  days,
            "off":   holidays,
        })

    print("─" * 50)
    print(f"   Total instruction days: {total_days}")

    expected = source.get("totalInstructionDays")
    if expected and total_days != expected:
        print(f"\n⚠  Source says {expected} instruction days, computed {total_days}. Check holidays.\n")
    else:
        print("\n   All counts look good.\n")

    return {
        "year":   source["year"],
        "school": source["school"],
        "terms":  processed_terms,
    }


# =============================================================================
# Emitters
# =============================================================================

def emit_js(data: dict) -> str:
    """Return a window.TRL_CALENDAR = {...}; JS assignment with a banner comment."""
    banner = f"/* Trillian academic calendar — {data['year']} {data['school']} | generated by zaphod calendar */"
    return f"{banner}\nwindow.TRL_CALENDAR = {json.dumps(data, separators=(',', ':'))};\n"


def emit_json(data: dict) -> str:
    """Return pretty-printed JSON string."""
    return json.dumps(data, indent=2) + "\n"
